apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        name: eks-charts
        kind: HelmRepository
  interval: 10m
  install:
    crds: CreateReplace
    timeout: 5m
  upgrade:
    crds: CreateReplace
    timeout: 5m
  values:
    clusterName: cloudland-main-cluster
    serviceAccount:
      create: false
      name: aws-load-balancer-controller