apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        name: jetstack
        kind: HelmRepository
  interval: 10m
  install:
    crds: CreateReplace
    timeout: 5m
  upgrade:
    crds: CreateReplace
    timeout: 5m
  values:
    installCRDs: "true"
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::730335410257:role/cert-manager-route53"