apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        name: ingress-nginx
        kind: HelmRepository
  interval: 10m
  install:
    crds: CreateReplace
    timeout: 5m
  upgrade:
    crds: CreateReplace
    timeout: 5m
  values:
    controller:
      watchIngressWithoutClass: true
      ingressClassResource:
        default: "true"
        enabled: "true"
      extraArgs:
        enable-ssl-passthrough: ""
      config:
        proxy-buffer-size: 64k
        client-header-buffer-size: 16k
        large-client-header-buffers: 4 64k
      service:
        targetPorts:
          http: http
          https: https
        annotations:
          alb.ingress.kubernetes.io/scheme: internet-facing
          service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
          service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-010f9bfe190376cd6,subnet-080d994b9ab57584d,subnet-0aa1425adc20aa112
          service.beta.kubernetes.io/aws-load-balancer-type: external
