apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-route53
spec:
  package: xpkg.upbound.io/upbound/provider-aws-route53:v1.6.0
  runtimeConfigRef:
    name: crossplane-aws-deploymentruntimeconfig