apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
spec:
  chart:
    spec:
      chart: crossplane
      sourceRef:
        name: crossplane-stable
        kind: HelmRepository
  interval: 10m
  install:
    crds: CreateReplace
    timeout: 5m
  upgrade:
    crds: CreateReplace
    timeout: 5m
