apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-api-operator
spec:
  chart:
    spec:
      chart: cluster-api-operator
      sourceRef:
        name: cluster-api-operator
        kind: HelmRepository
  interval: 10m
  install:
    crds: CreateReplace
    timeout: 5m
  upgrade:
    crds: CreateReplace
    timeout: 5m
  values:
    infrastructure: "vcluster"
    cert-manager:
      enabled: false
