apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  ports:
  #    - port: 80
  #      name: http
  #      targetPort: http-internal
  #      protocol: TCP
  selector:
    app: backend-service
